### ISSUE TITLE
prettier: lint-staged is not configured

### ISSUE THREAD

**Issue by Strulle** [co-IT/schematics#31] opened 2019-04-15 04:41 UTC
When running the prettier schematic, lint-staged is not configured (e.g. with `.lintstagedrc`). This causes an error when the pre-commit hook is running.  
`no config found`

We should add a template for this.

**Comment by GregOnNet** [comment] 2019-04-15 11:09
I experienced the same issue.
Until now I do not know exactly what the root cause is.
Sometimes it works as expected.

The template already exists: https://github.com/co-IT/schematics/tree/master/packages/schematics/src/prettier/templates/hook

**Comment by GregOnNet** [comment] 2019-04-24 10:53
Closing this issue for now since we cannot reproduce the described behaviour.

**Closed by GregOnNet** 2019-04-24 10:53 UTC
Labels: bug
